<div id="header">
<h1 class="title">CS2900 :- Topic 2 Lab</h1>
<h2 class="author">Hugh Shanahan and Tom Kuipers</h2>
</div>

The learning outcomes of this session are:

- To have an introductory understanding of matrix notation and related tools in NumPy.
- To become familiar with the concept of rotations and other linear transformations on Vectors.
- To apply the concept of adjacency matrices in determining numbers of walks between nodes in a graph.


# Grader

Just like last week, run the following code cells to set up the test functions for grading your work.

In [1]:
from client.api.notebook import Notebook
ok = Notebook('config/lab2.ok')

Assignment: Lab2
OK, version v1.18.1



# NumPy and Matrices

In [2]:
import numpy as np
import traceback as tb

- We can now discuss how one can set up arrays of more than one dimension. A simple <span class="math inline">2  ×  3</span> matrix can be defined by typing:

In [3]:
A = np.array([[1.5,2,3], [4,5,6]])

Defining a matrix is very much an extension of how vectors are defined, i.e. by adding additional rows.

Likewise, one can print out the contents of an array and find out its dimensions (always 2 for us), the number of rows and columns and how many entries it has in total.

In [4]:
A

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
A.ndim

2

In [6]:
A.shape

(2, 3)

In [7]:
A.size

6

We can use the same commands for a vector - NumPy does not make a distinction between a vector and a matrix. 

For NumPy, vectors are just a special instance of an array.

In [8]:
b = np.array([5.1,2.0,3.1])
b

array([5.1, 2. , 3.1])

In [9]:
b.ndim

1

In [10]:
b.shape

(3,)

In [11]:
b.size

3

<ul>
<li><p>NumPy allows building arrays with more than 2 indices, but we’re not going to explore such objects.</p></li>
<li><p>NumPy also has a class of objects which are explicitly referred to as of type <span>matrix</span>. Again, we’ll avoid using that class. All the objects we use (unless we explictely state otherwise will be of type <span>array</span>) even if we call them matrices or vectors.</p></li>
<li><p>A number of functions exist to create matrices without having to explictly enter the data in them. So</p>
</ul>

The code below creates an array **A** with the same number of rows and columns as above but with *zeros*.

In [12]:
A = np.zeros((2,3))

## CHECKPOINT 1 

- **Define a $5 \times 3$ matrix of zeros, `A_cp1`, using the syntax above.**
- **Create variables `nrow` and `ncol` that have the numbers of rows and columns of `A_cp1` respectively.**

**Note:** You must `np.shape` for this, **not** setting the variables manually.

In [22]:
A_cp1 = np.array([[1.5,2,3], [4,5,6],[1.5,2,3], [4,5,6], [1.5,2,3]])
nrow, ncol = A_cp1.shape

In [23]:
ok.grade('cp1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 7
    Failed: 0
[ooooooooook] 100.0% passed



{'passed': 7, 'failed': 0, 'locked': 0}

The code below creates an array **A** with the same number of rows and columns as above but with **ones**.



In [24]:
A = np.ones((2,3))

This code creates an array with the same dimensions as above but does not have **any** of the entries initialised. This can be faster than using zeros but you need to assign values and to be careful that you have done so (**why?**).

If you have a matrix and you want to create a similarly sized matrix with one of the above three properties then you can do that by using the commands *zeros_like*, *ones_like* and *empty_like*.

Type:

In [25]:
A = np.empty((2,3))

In [26]:
B = np.array([[1.5,2],[3, 4],[5,6]])

In [27]:
A = np.zeros_like(B)

In [28]:
# \n\n just puts two line breaks between the output of B and A.
print(B,"\n\n",A)

[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]] 

 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [29]:
A = np.ones_like(B)

In [30]:
print(B,"\n\n",A)

[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]] 

 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
A = np.empty_like(B)

In [32]:
print(B,"\n\n",A)

[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]] 

 [[1. 1.]
 [1. 1.]
 [1. 1.]]


## CHECKPOINT 2

**Create a matrix `X` that has the same dimensions as the matrix**

$$\begin{pmatrix} 
1&1&2&2 \\
3&2&1&8
\end{pmatrix}$$

**with _ones_ in all its entries.**

In [37]:
X = np.ones((2,4))



In [38]:
ok.grade('cp2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 4
    Failed: 0
[ooooooooook] 100.0% passed



{'passed': 4, 'failed': 0, 'locked': 0}

We can create an identity matrix for square matrices like so:

In [39]:
A = np.eye(4)
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<p>Finally, we can update individual elements as we would if we were accessing a regular 2D array.</p>

In [40]:
A[0,1] = 7.0
A

array([[1., 7., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

One can compute the vector that is created by multiplying a matrix with a vector using the `np.matmul(A, b)` function. Type:

In [41]:
b = np.array([5,2])

In [42]:
A = np.array([[0,4],[1,1]])

In [43]:
np.matmul(A,b)

array([8, 7])

This is a simple $2 \times 2$ example but we can pick different matrix sizes. Type:

In [54]:
b = np.array([5,2,1])

In [55]:
A = np.array([[0,4,0],[1,1,1]])

In [56]:
np.matmul(A,b)

array([8, 8])

<p>But we need to be careful about the dimensions! Type</p>

In [ ]:
A = np.array([[0,4],[0,1],[1,1]])

In [ ]:
try:
    print(np.matmul(A,b))
except :
    print(tb.format_exc())

**What happened here?** Try to understand this before moving on.

One can likewise multiply matrices using the `np.matmul(A,b)` command. Type:

In [51]:
A = np.array([[0,4],[1,1]])

In [52]:
B = np.array([[1,2],[0,1]])

In [53]:
np.matmul(A,B)

array([[0, 4],
       [1, 3]])

## CHECKPOINT 3

**If**
$$
{\mathbf R} = \begin{pmatrix}3& 2 & 1 \\ 1 & -1 & 2\end{pmatrix}
$$
**and**
$$
\underline{x} = \begin{pmatrix} 1 \\ 2 \\ -1\end{pmatrix}
$$

- **Define `R` and `x` as above.**
- **Create a vector `y` such that** $\underline{y}  = {\mathbf R}\underline{x}$.

In [63]:
R = np.array([[3,2,1], [1,-1,2]])
x = np.array([1,2,-1])
y = np.matmul(R,x)


In [64]:
ok.grade('cp3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 4
    Failed: 0
[ooooooooook] 100.0% passed



{'passed': 4, 'failed': 0, 'locked': 0}

Finally, one can compute the inverse of matrices using the `invert` function which is part of the `numpy.linalg` module. 

Type:

In [66]:
print(np.linalg.inv(A))

LinAlgError: Last 2 dimensions of the array must be square

<p>but we always have to aware that many matrices are singular (non-invertible) !</p>

In [67]:
A = np.array([[0,4],[0,8]])

In [68]:
try:
    print(np.linalg.inv(A))
except :
    print(tb.format_exc())

Traceback (most recent call last):
  File "/tmp/ipykernel_59/1533433719.py", line 2, in <module>
    print(np.linalg.inv(A))
  File "<__array_function__ internals>", line 6, in inv
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix



# Rotations and Stretching

In the lectures, we discussed matrices that rotate or those that stretch (or ‘scrunch’). In this part of the lab exercise, we will extend this case to 3 dimensions.

We noted that a rotation in **2** dimensions over an angle $\theta$ is:
$$
\begin{pmatrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta
\end{pmatrix}
$$

**How could this be extended to three dimensions?** The trick is to think of this
in steps. In particular, let us suppose we want to do a rotation in 3 dimensional space
but we only want to do  a rotation in the **x-y** plane. 

This means that we want to rotate the $x$ and $y$ coordinates but leave $z$ alone. What we want to do is, extend the above rotation **without** changing the $z$ coordinate. This can be achieved with:

$$
\begin{pmatrix}
\cos \theta & -\sin \theta & 0 \\
\sin \theta & \cos \theta  & 0 \\
0 & 0 & 1
\end{pmatrix}
$$

## CHECKPOINT 4

**Write a Python function `thetaRot` that accepts a single argument `theta` which is a floating point number and returns a $3 \times 3$ NumPy matrix of the above form (i.e. `theta` = $\theta $ ).**

**Hint:** You will need to use the `math` library. 

Using pen and paper, compute what the matrix should be if $\theta = 45$ degrees ($\pi/4$). 

**Note:** $\cos{\pi/4} = \sin{pi/4} = \frac{1}{\sqrt{2}}$. 

- **Check if `thetaRot` returns that matrix.**

In [ ]:
import math

def thetaRot(float theta):
    


In [ ]:
ok.grade('cp4')

## CHECKPOINT 5

**Write a Python function `Rx` which has two arguments, a $3 \times 3$ NumPy matrix, `R`, and a 3-dimensional vector, `x`, and returns the vector $\underline{y} = \mathbf{R} \underline{x}$.**

**If `R` is the output from thetaRot when theta = $\pi/4$ and `x` is** 
$$
\begin{pmatrix}
1 \\
1 \\
1 
\end{pmatrix}
$$

- **Compute $\mathbf{R} \underline{x}$ with pen and paper.**
- **Define a variable `Rx_cp5` and set it equal to the result of your function `Rx` with the `R` and `x` defined above.**
- **Check if the output of `Rx` is the same as what you have written down.**

In [ ]:
# Your code here...



In [ ]:
ok.grade('cp5')

Correspondingly, if we wanted to do the same operation with a rotation of $\phi$ in the **y-z**
plane, then the rotation matrix is:

$$
\begin{pmatrix}
1 & 0 & 0 \\
0 & \cos \phi & -\sin \phi  \\
0 & \sin \phi & \cos \phi
\end{pmatrix}
$$

**QUESTION:** What would be the corresponding matrix for the **x-z** plane?

As an aside, it turns out that <em> any </em>  rotation in 3-dimensional space can be represented as a series of rotations in 2-dimensional planes, though those planes are
not as straightforward as the above. These are the so called *Euler angles*, 
but we will not consider this any further.

The corresponding Python code to compute a rotation `R1` in the **x-y** plane when $\theta=\pi/4$ and a rotation `R2` which is in the **y-z** plane when $\phi=\pi/8$ is


In [ ]:
import math
from math import pi

theta = pi/4.0
cT = math.cos(theta)
sT = math.sin(theta)
R1 = np.array([[cT,-sT,0],[sT,cT,0],[0,0,1]])
phi = pi/8.0
cP = math.cos(phi)
sP = math.sin(phi)
R2 = np.array([[1,0,0], [0,cP,-sP],[0,sP,cP]])


## EXTENSION CHECKPOINT (NOT GRADED)

**Write a Python function `generalRot` that has two arguments, a string `plane` and an angle `t`.**

- **The string plane can be `"xy"`, `"yz"` or `"xz"` to indicate which plane the rotation is being calculated in.**
- **If it is not one of these, then it returns the message `"Plane must xy, yz or xz"`.**
- **If plane is correct then it returns the corresponding $3 \times 3$ NumPy matrix corresponding to a rotation of `t` in that plane.**

In [ ]:
# Your code here...



We can compute how vectors are transformed under these matrices. It is worth
asking what happens to dot products of vectors before and after rotation.

## CHECKPOINT 6

**Write a function `compare` that accepts two 3 dimensional NumPy vectors `x` and `y`, and a $3 \times 3$ NumPy matrix `R`.**

**`compare` should return a _tuple_ of the form `(l1,l2,d1,d2)` where `l1` is the length of `x`, `l2` is length of `x` multiplied by `R`.**

**`d1` is the dot product of `x` and `y` and `d2` is the dot product of** $ \bf{R} \underline{x}$ **and** $ \bf{R} \underline{y} $. 

<b>Apply this function for</b>

$$
\underline{x} = 
\begin{pmatrix} 
1 \\
1 \\
1 
\end{pmatrix}
$$


$$
\underline{y} = 
\begin{pmatrix} 
1 \\
1 \\
-1 
\end{pmatrix}
$$

**and `R` = `R1` (described above).**


**`l1` should be equal to  `l2` and `d1` should be equal to `d2`. _Why is this?_**

**Extension question: What do you observe about `d1` and `d2`? If they are different, then by how much are they different?**

**Print out `np.array(compare(x, y, R))` (which just converts the tuple to a Numpy array) and see what you observe... If you are curious about this, please ask.**

In [ ]:
# Your code here...



In [ ]:
ok.grade('cp6')

We can compute the inverse of `R1` simply by using the `linalg.inv` function
but it's also possible to determine it directly (i.e. by a formula like how we defined `R1` initially).

## CHECKPOINT 7

**Create a $3 \times 3$ matrix, `R1m`, that is the inverse of `R1` by using a formula.**

**Hint: Think about the angle of rotation in the inverse.**

**Then, compute a $3 \times 3$ matrix, `R1inv`, that is the inverse of `R1` using the `linalg.inv` function.**

In [ ]:
# Your code here...



In [ ]:
ok.grade('cp7')

## CHECKPOINT 8

**Write a function `sqDiffMatrices` that accepts two arguments; two $3 \times 3$ NumPy matrices, `A`, `B`, and returns:**

$$ \sum_{i,j} (A_{i,j} - B_{i,j})^2 $$. 

**Compute `sqDiffMatrices(R1m, R1inv)`. _What value should this be?_**

In [ ]:
# Your code here...



In [ ]:
ok.grade('cp8')

Instead of thinking of one rotation, we can put rotations together by multiplying them together. In the case above, a composite rotation
`np.matmul(R1,R2)` corresponds to first applying the rotation `R2` followed by the
rotation `R1`.

## CHECKPOINT 9

- **Compute the $3 \times 3$ matrix, `A_cp9`, which corresponds to the above rotation (`R1` followed by `R2`).**

- **Compute the $3 \times 3$ matrix, `B_cp9`, which corresponds to the rotation `R2` followed by `R1`.**

- **Compute `sqDiffMatrices(A_cp9, B_cp9)`. Is this value close to zero? _Why?_**

In [ ]:
# Your code here...



In [ ]:
ok.grade('cp9')

<h2 id="Stretching">Stretching</h2>

The corresponding stretch matrix in 3 dimensions is:

$$
\mathbf{S} = 
\begin{pmatrix}
a & 0 & 0 \\
0 & b & 0 \\
0 & 0 & c
\end{pmatrix}
$$

## CHECKPOINT 10

**From the lecture notes, there is a formula for the inverse of such a matrix.** 

- **Define `S` when `a` = 5, `b` = 4 and `c` = 2.** 
- **Compute `S_inv_form` which is the inverse of `S` calculated using the formula.**
- **Compute `S_inv_calc` which is the inverse of `S`   using the `linalg.inv` function.**
- **Calculate `sqDiffMatrices(S_inv_form, S_inv_calc)`. Is this value close to zero? _Why?_**

In [ ]:
# Your code here...



In [ ]:
ok.grade('cp10')

<h1 id="Adjacency-matrix">Adjacency matrix</h1>

As discussed in the lectures, the adjacency matrix of a graph $\mathbf{N}$ can be used to
compute how many paths exists between two arbitrary vertices of length $p$, by looking at
the corresponding entry for $\mathbf{N}^p$. For example you can find the number of paths of length 2 between any pair 
of vertices by computing $\mathbf{N}^2$.

## CHECKPOINT 11

- **Define the $4 \times 4$ NumPy matrix, `N`, corresponding to the definition in the notes of Topic 2.**
- **Compute `Nsq` = $\mathbf{N}^2$ and `Ncb` = $\mathbf{N}^3$**

**Check if they match with what you expect if you looked at the graph and computed the number of paths by hand.**

In [ ]:
# Your code here...



In [ ]:
ok.grade('cp11')

# Grading your Checkpoints

Use the code cell below to grade your checkpoints and run all the tests. For this lab, there are **11** graded checkpoints. You should aim for at least **75%** on each lab sheet.

Extension checkpoints are not graded but you are encouraged to do them if you have time and have finished the lab sheet! You will be expected to know how to write code using Numpy in the exam, so they are good practice.

In [ ]:
ok.score()

# Extension Work

If you have finished the rest of the checkpoints then you are encouraged to attempt these extension work exercises to further your understanding! Do let us know if you manage to complete them.

## Extension Work 1

**If one has a graph of $m$ nodes, then the maximum possible path between two nodes is $m$ (satisfy yourself that this is true). This gives a method (albeit a deeply inefficient one)  to determine if a graph is disconnected, i.e. that there are at least one pair of nodes that are not connected through some path.**

**If we have a corresponding adjacency matrix
$\mathbf{A}$ then, if we can compute $\mathbf{A}^2$, $\mathbf{A}^3$, $\dots$ $\mathbf{A}^m$
and we find that in all of these cases, we find that a particular entry in this sequence of matrices remains zero, then no path lies between those nodes.**

- **Write a function `checkDisconnected` that takes a single argument `A` which is an $n \times n$ adjacency matrix.** 
- **`checkDisconnected` returns a boolean that indicates if it is disconnected graph.** 

**Note:** Every pair of nodes has to be checked to see if one has no path of any length from 1 to n.**


In [ ]:
# Your code here...



## Extension Work 2

The Internet Movie DataBase [IMDB.com](https://www.imdb.com/) provides encyclopedic amounts of information about Movies and Television programmes. They make available [subsets of their data](https://www.imdb.com/interfaces/) which we can make use of. In the notebook folder, there is a file called actorsShort.tsv which is 1,000 lines of data from the subset (the subset available from IMDB is around 41 million lines long). An example line from this file is as follows:

`tt0000005       2       nm0653042       actor   \N      ["Assistant"]`

The entries are separated by tabs and the entries of interest are in the first and third columns (i.e. `tt0000005` and `nm0653042` in the above example). The first entry is an id to identify a Movie title. The third entry is an id to identify an actor. 

In network analysis, there has been much research into Actor networks, i.e. creating graphs where actors represent nodes and there is an edge between the nodes if two actors were in the same movie. With this dataset and adjacency matrices, we can explore this. 

### Task 1

Write a function that will read in the above file and return a NumPy matrix which has the adjacency matrix corresponding to the graph of the actor network described above. 

You will first need to figure out how many actors there are, which will inform you of the size of the matrix. Then you need to build the matrix. 

**Tip:** You might it useful to create dictionaries of the data initially.

In [ ]:
# Your code here...



### Task 2

Write another function that accepts two arguments, one with the adjacency matrix `A` and the other an integer with the path length `n`. The function will return the fraction of pairs of nodes that are connected by a path of length `n`. 

One should note:
* The total possible number of pairs of nodes is `n`(`n` + 1) / 2
* Matrix multiplication is an ${\cal{O}}(N^2)$ operation so avoid trying this with large values of `n`
* The data set provided is just a small subset of the entire IMDB data set so it's likely that the graph will be disconnected.

In [ ]:
# Your code here...

